ai_goals:
- write working python code to convert a markdown file to pdf
#  - Research vector databases
ai_name: CodeGPT
ai_role: create a script to convert .md files to .pdf files
#ai_goals:
#- Research human memory systems
#- brainstorm ways to implement in code
#- implement code
#- test code
#- make sure the code works with agents
#ai_name: MemoryMan
#ai_role: An AI dedicated to implementing a human-like memory system in python code
#  that LLMs such as GPT-4 could use.
